// ─── Departments ─────────────────────────────────────────────────────────────
export const departments = [
  { id: 'COE', name: 'College of Engineering', code: 'COE', director: 'Dr. Ricardo Santos' },
  { id: 'DIT', name: 'Department of Information Technology', code: 'DIT', director: 'Prof. Maria Reyes' },
  { id: 'CBA', name: 'College of Business Administration', code: 'CBA', director: 'Dr. Jose Mendoza' },
  { id: 'CED', name: 'College of Education', code: 'CED', director: 'Dr. Ana Villanueva' },
  { id: 'DNS', name: 'Department of Natural Sciences', code: 'DNS', director: 'Dr. Carlos Tan' },
]

// ─── Positions ────────────────────────────────────────────────────────────────
export const positions = [
  {
    id: 'pos-001',
    title: 'Assistant Professor I',
    department: 'DIT',
    departmentName: 'Department of Information Technology',
    status: 'open',
    slotsAvailable: 2,
    slotsFilled: 0,
    targetType: 'both',
    deadline: '2025-07-31',
    createdAt: '2025-05-01',
    description:
      'We are seeking a qualified Assistant Professor I to join the Department of Information Technology. The successful candidate will teach undergraduate IT courses, engage in research, and contribute to departmental activities.',
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'pos-002',
    title: 'Instructor III',
    department: 'COE',
    departmentName: 'College of Engineering',
    status: 'open',
    slotsAvailable: 3,
    slotsFilled: 1,
    targetType: 'external',
    deadline: '2025-08-15',
    createdAt: '2025-05-03',
    description:
      'The College of Engineering invites applications for three Instructor III positions. Applicants should have a background in engineering disciplines and a commitment to teaching excellence.',
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'pos-003',
    title: 'Associate Professor II',
    department: 'CBA',
    departmentName: 'College of Business Administration',
    status: 'open',
    slotsAvailable: 1,
    slotsFilled: 0,
    targetType: 'internal',
    deadline: '2025-06-30',
    createdAt: '2025-04-20',
    description:
      'The College of Business Administration seeks an Associate Professor II for internal promotion. Candidates must have demonstrated research output and leadership in academic programs.',
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'pos-004',
    title: 'College Dean',
    department: 'CED',
    departmentName: 'College of Education',
    status: 'closed',
    slotsAvailable: 1,
    slotsFilled: 1,
    targetType: 'both',
    deadline: '2025-03-31',
    createdAt: '2025-01-15',
    description:
      'The College of Education conducted a search for a new College Dean. This position has been closed as the search has concluded.',
    hiringRound: 'AY 2024-2025 Second Semester',
  },
  {
    id: 'pos-005',
    title: 'Instructor I',
    department: 'DNS',
    departmentName: 'Department of Natural Sciences',
    status: 'open',
    slotsAvailable: 2,
    slotsFilled: 0,
    targetType: 'external',
    deadline: '2025-07-15',
    createdAt: '2025-05-10',
    description:
      'The Department of Natural Sciences is hiring two Instructor I positions for laboratory and lecture courses in Biology, Chemistry, and Physics.',
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'pos-006',
    title: 'Assistant Professor III',
    department: 'COE',
    departmentName: 'College of Engineering',
    status: 'open',
    slotsAvailable: 1,
    slotsFilled: 0,
    targetType: 'both',
    deadline: '2025-08-01',
    createdAt: '2025-05-12',
    description:
      'The College of Engineering invites applications for Assistant Professor III. The candidate should have a doctorate in engineering and active research agenda.',
    hiringRound: 'AY 2025-2026 First Semester',
  },
]

// ─── Criteria (for DIT Assistant Professor I) ─────────────────────────────────
export const criteria = [
  {
    id: 'crit-001',
    positionId: 'pos-001',
    name: 'Educational Attainment',
    dataType: 'numeric',
    weight: 0.30,
    required: true,
    minValue: 1,
    maxValue: 5,
    description: 'Level of educational attainment (1=Bachelor, 2=PG Units, 3=Master, 4=PhD Units, 5=Doctorate)',
  },
  {
    id: 'crit-002',
    positionId: 'pos-001',
    name: 'Teaching Experience (years)',
    dataType: 'numeric',
    weight: 0.25,
    required: true,
    minValue: 0,
    maxValue: 20,
    description: 'Number of years of teaching experience in higher education',
  },
  {
    id: 'crit-003',
    positionId: 'pos-001',
    name: 'Research Publications',
    dataType: 'numeric',
    weight: 0.20,
    required: false,
    minValue: 0,
    maxValue: 10,
    description: 'Number of peer-reviewed publications in the past 5 years',
  },
  {
    id: 'crit-004',
    positionId: 'pos-001',
    name: 'Professional Certifications',
    dataType: 'boolean',
    weight: 0.15,
    required: false,
    minValue: null,
    maxValue: null,
    description: 'Holds relevant professional certifications (e.g., PRC license, industry cert)',
  },
  {
    id: 'crit-005',
    positionId: 'pos-001',
    name: 'Specialization Alignment',
    dataType: 'select',
    weight: 0.10,
    required: true,
    minValue: null,
    maxValue: null,
    description: 'Degree of specialization alignment with department needs',
  },
]

// ─── Applicants ──────────────────────────────────────────────────────────────
export const applicants = [
  {
    id: 'app-001',
    firstName: 'Juan',
    lastName: 'dela Cruz',
    fullName: 'Juan dela Cruz',
    email: 'juan.delacruz@email.com',
    phone: '+63 917 123 4567',
    type: 'external',
    department: 'DIT',
    departmentName: 'Department of Information Technology',
    positionId: 'pos-001',
    positionTitle: 'Assistant Professor I',
    wsmScore: 0.8742,
    status: 'for_interview',
    appliedDate: '2025-05-15',
    accountCreated: '2025-05-14',
    profileCompleted: true,
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'app-002',
    firstName: 'Maria',
    lastName: 'Santos',
    fullName: 'Maria Santos',
    email: 'maria.santos@email.com',
    phone: '+63 918 234 5678',
    type: 'external',
    department: 'DIT',
    departmentName: 'Department of Information Technology',
    positionId: 'pos-001',
    positionTitle: 'Assistant Professor I',
    wsmScore: 0.7651,
    status: 'applied',
    appliedDate: '2025-05-17',
    accountCreated: '2025-05-16',
    profileCompleted: true,
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'app-003',
    firstName: 'Robert',
    lastName: 'Reyes',
    fullName: 'Robert Reyes',
    email: 'robert.reyes@university.edu.ph',
    phone: '+63 919 345 6789',
    type: 'internal',
    department: 'COE',
    departmentName: 'College of Engineering',
    positionId: 'pos-006',
    positionTitle: 'Assistant Professor III',
    wsmScore: 0.9123,
    status: 'hired',
    appliedDate: '2025-05-10',
    accountCreated: '2025-04-01',
    profileCompleted: true,
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'app-004',
    firstName: 'Ana',
    lastName: 'Gonzalez',
    fullName: 'Ana Gonzalez',
    email: 'ana.gonzalez@email.com',
    phone: '+63 920 456 7890',
    type: 'external',
    department: 'CBA',
    departmentName: 'College of Business Administration',
    positionId: 'pos-003',
    positionTitle: 'Associate Professor II',
    wsmScore: 0.6234,
    status: 'for_review',
    appliedDate: '2025-05-12',
    accountCreated: '2025-05-11',
    profileCompleted: false,
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'app-005',
    firstName: 'Miguel',
    lastName: 'Torres',
    fullName: 'Miguel Torres',
    email: 'miguel.torres@university.edu.ph',
    phone: '+63 921 567 8901',
    type: 'internal',
    department: 'DIT',
    departmentName: 'Department of Information Technology',
    positionId: 'pos-001',
    positionTitle: 'Assistant Professor I',
    wsmScore: 0.8891,
    status: 'for_interview',
    appliedDate: '2025-05-08',
    accountCreated: '2025-03-15',
    profileCompleted: true,
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'app-006',
    firstName: 'Liza',
    lastName: 'Fernandez',
    fullName: 'Liza Fernandez',
    email: 'liza.fernandez@email.com',
    phone: '+63 922 678 9012',
    type: 'external',
    department: 'DNS',
    departmentName: 'Department of Natural Sciences',
    positionId: 'pos-005',
    positionTitle: 'Instructor I',
    wsmScore: 0.5412,
    status: 'applied',
    appliedDate: '2025-05-18',
    accountCreated: '2025-05-18',
    profileCompleted: false,
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'app-007',
    firstName: 'Paolo',
    lastName: 'Cruz',
    fullName: 'Paolo Cruz',
    email: 'paolo.cruz@email.com',
    phone: '+63 923 789 0123',
    type: 'external',
    department: 'COE',
    departmentName: 'College of Engineering',
    positionId: 'pos-002',
    positionTitle: 'Instructor III',
    wsmScore: 0.7890,
    status: 'applied',
    appliedDate: '2025-05-14',
    accountCreated: '2025-05-13',
    profileCompleted: true,
    hiringRound: 'AY 2025-2026 First Semester',
  },
  {
    id: 'app-008',
    firstName: 'Carmen',
    lastName: 'Villanueva',
    fullName: 'Carmen Villanueva',
    email: 'carmen.villanueva@university.edu.ph',
    phone: '+63 924 890 1234',
    type: 'internal',
    department: 'CBA',
    departmentName: 'College of Business Administration',
    positionId: 'pos-003',
    positionTitle: 'Associate Professor II',
    wsmScore: 0.8345,
    status: 'for_review',
    appliedDate: '2025-05-09',
    accountCreated: '2025-02-20',
    profileCompleted: true,
    hiringRound: 'AY 2025-2026 First Semester',
  },
]

// ─── Score Breakdown (for app-001, Juan dela Cruz) ────────────────────────────
export const scoreBreakdown = [
  {
    criterionName: 'Educational Attainment',
    weight: 0.30,
    rawValue: '4',
    normalizedScore: 0.75,
    weightedScore: 0.2250,
  },
  {
    criterionName: 'Teaching Experience (years)',
    weight: 0.25,
    rawValue: '6',
    normalizedScore: 0.30,
    weightedScore: 0.0750,
  },
  {
    criterionName: 'Research Publications',
    weight: 0.20,
    rawValue: '5',
    normalizedScore: 0.50,
    weightedScore: 0.1000,
  },
  {
    criterionName: 'Professional Certifications',
    weight: 0.15,
    rawValue: 'Yes',
    normalizedScore: 1.00,
    weightedScore: 0.1500,
  },
  {
    criterionName: 'Specialization Alignment',
    weight: 0.10,
    rawValue: 'High',
    normalizedScore: 0.9467,
    weightedScore: 0.0947,
  },
]

// ─── Status History (for app-001) ─────────────────────────────────────────────
export const statusHistory = [
  {
    id: 'sh-001',
    previousStatus: 'applied',
    newStatus: 'for_interview',
    notes: 'Initial screening passed. Candidate scores above threshold of 0.85.',
    changedBy: 'Admin User',
    timestamp: '2025-05-17T10:30:00',
  },
  {
    id: 'sh-002',
    previousStatus: null,
    newStatus: 'applied',
    notes: 'Application submitted by candidate.',
    changedBy: 'System',
    timestamp: '2025-05-15T14:22:00',
  },
]

// ─── Hiring Rounds ────────────────────────────────────────────────────────────
export const hiringRounds = [
  {
    id: 'hr-001',
    name: 'AY 2025-2026 First Semester',
    semester: '1st Semester',
    academicYear: '2025-2026',
    startDate: '2025-05-01',
    endDate: '2025-08-31',
    status: 'active',
  },
  {
    id: 'hr-002',
    name: 'AY 2024-2025 Second Semester',
    semester: '2nd Semester',
    academicYear: '2024-2025',
    startDate: '2024-11-01',
    endDate: '2025-04-30',
    status: 'closed',
  },
  {
    id: 'hr-003',
    name: 'AY 2024-2025 First Semester',
    semester: '1st Semester',
    academicYear: '2024-2025',
    startDate: '2024-05-01',
    endDate: '2024-10-31',
    status: 'archived',
  },
]

// ─── Notifications ────────────────────────────────────────────────────────────
export const notifications = [
  {
    id: 'notif-001',
    recipientName: 'Juan dela Cruz',
    recipientEmail: 'juan.delacruz@email.com',
    type: 'status_change',
    subject: 'Your application status has been updated to For Interview',
    body: 'Dear Juan, your application for Assistant Professor I (DIT) has been updated to For Interview. Please await further instructions.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-05-17T10:31:00',
  },
  {
    id: 'notif-002',
    recipientName: 'Maria Santos',
    recipientEmail: 'maria.santos@email.com',
    type: 'application_received',
    subject: 'Application Received — Assistant Professor I',
    body: 'Dear Maria, we have received your application for the position of Assistant Professor I at the Department of Information Technology.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-05-17T08:45:00',
  },
  {
    id: 'notif-003',
    recipientName: 'Robert Reyes',
    recipientEmail: 'robert.reyes@university.edu.ph',
    type: 'status_change',
    subject: 'Congratulations — You have been hired for Assistant Professor III',
    body: 'Dear Robert, congratulations! You have been selected for the Assistant Professor III position in the College of Engineering.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-05-16T15:00:00',
  },
  {
    id: 'notif-004',
    recipientName: 'Liza Fernandez',
    recipientEmail: 'liza.fernandez@email.com',
    type: 'application_received',
    subject: 'Application Received — Instructor I',
    body: 'Dear Liza, we have received your application for the position of Instructor I at the Department of Natural Sciences.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-05-18T09:15:00',
  },
  {
    id: 'notif-005',
    recipientName: 'Carmen Villanueva',
    recipientEmail: 'carmen.villanueva@university.edu.ph',
    type: 'status_change',
    subject: 'Your application status has been updated to For Review',
    body: 'Dear Carmen, your application for Associate Professor II (CBA) is now under review.',
    channel: 'in_app',
    deliveryStatus: 'sent',
    sentAt: '2025-05-16T11:20:00',
  },
  {
    id: 'notif-006',
    recipientName: 'Ana Gonzalez',
    recipientEmail: 'ana.gonzalez@email.com',
    type: 'status_change',
    subject: 'Your application is now For Review',
    body: 'Dear Ana, your application for Associate Professor II is currently being reviewed by the committee.',
    channel: 'email',
    deliveryStatus: 'failed',
    sentAt: '2025-05-15T13:00:00',
  },
  {
    id: 'notif-007',
    recipientName: 'Miguel Torres',
    recipientEmail: 'miguel.torres@university.edu.ph',
    type: 'pool_invitation',
    subject: 'Invitation to Join Applicant Pool',
    body: 'Dear Miguel, you are invited to join the active applicant pool for the upcoming hiring round.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-05-14T16:30:00',
  },
  {
    id: 'notif-008',
    recipientName: 'Paolo Cruz',
    recipientEmail: 'paolo.cruz@email.com',
    type: 'application_received',
    subject: 'Application Received — Instructor III',
    body: 'Dear Paolo, we have received your application for the position of Instructor III at the College of Engineering.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-05-14T10:05:00',
  },
  {
    id: 'notif-009',
    recipientName: 'Dr. Ricardo Santos',
    recipientEmail: 'ricardo.santos@university.edu.ph',
    type: 'account_created',
    subject: 'Your MCDSS Staff Account Has Been Created',
    body: 'Dear Dr. Santos, your MCDSS staff account has been created. Please use the temporary credentials to log in.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-04-01T09:00:00',
  },
  {
    id: 'notif-010',
    recipientName: 'Prof. Maria Reyes',
    recipientEmail: 'maria.reyes@university.edu.ph',
    type: 'account_created',
    subject: 'Your MCDSS Staff Account Has Been Created',
    body: 'Dear Prof. Reyes, your MCDSS staff account has been created. Please use the temporary credentials to log in.',
    channel: 'email',
    deliveryStatus: 'sent',
    sentAt: '2025-04-01T09:05:00',
  },
]

// ─── Pool Members ─────────────────────────────────────────────────────────────
export const poolMembers = [
  {
    id: 'pool-001',
    applicantName: 'Ana Gonzalez',
    email: 'ana.gonzalez@email.com',
    type: 'external',
    originalPosition: 'Associate Professor II',
    department: 'CBA',
    departmentName: 'College of Business Administration',
    originalRound: 'AY 2024-2025 Second Semester',
    poolStatus: 'pool_active',
    reengagementSent: true,
    confirmedInterest: 'pending',
  },
  {
    id: 'pool-002',
    applicantName: 'Liza Fernandez',
    email: 'liza.fernandez@email.com',
    type: 'external',
    originalPosition: 'Instructor I',
    department: 'DNS',
    departmentName: 'Department of Natural Sciences',
    originalRound: 'AY 2024-2025 Second Semester',
    poolStatus: 'reengaged',
    reengagementSent: true,
    confirmedInterest: 'yes',
  },
  {
    id: 'pool-003',
    applicantName: 'Paolo Cruz',
    email: 'paolo.cruz@email.com',
    type: 'external',
    originalPosition: 'Instructor III',
    department: 'COE',
    departmentName: 'College of Engineering',
    originalRound: 'AY 2024-2025 First Semester',
    poolStatus: 'pool_active',
    reengagementSent: false,
    confirmedInterest: 'no',
  },
  {
    id: 'pool-004',
    applicantName: 'Rodrigo Aquino',
    email: 'rodrigo.aquino@email.com',
    type: 'external',
    originalPosition: 'Instructor I',
    department: 'DNS',
    departmentName: 'Department of Natural Sciences',
    originalRound: 'AY 2024-2025 Second Semester',
    poolStatus: 'pool_inactive',
    reengagementSent: true,
    confirmedInterest: 'no',
  },
  {
    id: 'pool-005',
    applicantName: 'Rina Castillo',
    email: 'rina.castillo@email.com',
    type: 'external',
    originalPosition: 'Assistant Professor I',
    department: 'DIT',
    departmentName: 'Department of Information Technology',
    originalRound: 'AY 2024-2025 First Semester',
    poolStatus: 'reengaged',
    reengagementSent: true,
    confirmedInterest: 'yes',
  },
]

// ─── Assignment Run ──────────────────────────────────────────────────────────
export const assignmentRun = {
  id: 'arun-001',
  runAt: '2025-05-16T08:00:00',
  status: 'completed',
  objectiveScore: 4.8723,
  totalAssigned: 6,
  positionsFullyFilled: 2,
  scope: {
    applicantTypes: ['external', 'internal'],
    departments: ['DIT', 'COE', 'CBA', 'DNS'],
    positionCount: 5,
    applicantCount: 8,
  },
}

export const assignmentResults = [
  {
    id: 'ar-001',
    applicantName: 'Juan dela Cruz',
    position: 'Assistant Professor I',
    department: 'DIT',
    wsmScore: 0.8742,
    isAssigned: true,
    objectiveScore: 0.8742,
  },
  {
    id: 'ar-002',
    applicantName: 'Miguel Torres',
    position: 'Assistant Professor I',
    department: 'DIT',
    wsmScore: 0.8891,
    isAssigned: true,
    objectiveScore: 0.8891,
  },
  {
    id: 'ar-003',
    applicantName: 'Robert Reyes',
    position: 'Assistant Professor III',
    department: 'COE',
    wsmScore: 0.9123,
    isAssigned: true,
    objectiveScore: 0.9123,
  },
  {
    id: 'ar-004',
    applicantName: 'Carmen Villanueva',
    position: 'Associate Professor II',
    department: 'CBA',
    wsmScore: 0.8345,
    isAssigned: true,
    objectiveScore: 0.8345,
  },
  {
    id: 'ar-005',
    applicantName: 'Paolo Cruz',
    position: 'Instructor III',
    department: 'COE',
    wsmScore: 0.7890,
    isAssigned: true,
    objectiveScore: 0.7890,
  },
  {
    id: 'ar-006',
    applicantName: 'Ana Gonzalez',
    position: 'Associate Professor II',
    department: 'CBA',
    wsmScore: 0.6234,
    isAssigned: false,
    objectiveScore: 0.6234,
  },
  {
    id: 'ar-007',
    applicantName: 'Maria Santos',
    position: 'Assistant Professor I',
    department: 'DIT',
    wsmScore: 0.7651,
    isAssigned: false,
    objectiveScore: 0.7651,
  },
  {
    id: 'ar-008',
    applicantName: 'Liza Fernandez',
    position: 'Instructor I',
    department: 'DNS',
    wsmScore: 0.5412,
    isAssigned: false,
    objectiveScore: 0.5412,
  },
]

// ─── Faculty Workload ─────────────────────────────────────────────────────────
export const facultyWorkload = [
  {
    id: 'fw-001',
    facultyName: 'Dr. Robert Reyes',
    courseCode: 'CS101',
    courseName: 'Introduction to Programming',
    units: 3,
    semester: '1st Semester',
    academicYear: '2025-2026',
  },
  {
    id: 'fw-002',
    facultyName: 'Dr. Robert Reyes',
    courseCode: 'CS201',
    courseName: 'Data Structures and Algorithms',
    units: 3,
    semester: '1st Semester',
    academicYear: '2025-2026',
  },
  {
    id: 'fw-003',
    facultyName: 'Prof. Maria Santos',
    courseCode: 'IT301',
    courseName: 'Web Development',
    units: 3,
    semester: '1st Semester',
    academicYear: '2025-2026',
  },
  {
    id: 'fw-004',
    facultyName: 'Prof. Miguel Torres',
    courseCode: 'IT401',
    courseName: 'Database Systems',
    units: 3,
    semester: '1st Semester',
    academicYear: '2025-2026',
  },
]

// ─── Staff Accounts ───────────────────────────────────────────────────────────
export const staffAccounts = [
  {
    id: 'staff-001',
    firstName: 'Ricardo',
    lastName: 'Santos',
    fullName: 'Dr. Ricardo Santos',
    email: 'ricardo.santos@university.edu.ph',
    accountStatus: 'active',
    hasTempPassword: false,
    createdAt: '2025-04-01T09:00:00',
  },
  {
    id: 'staff-002',
    firstName: 'Maria',
    lastName: 'Reyes',
    fullName: 'Prof. Maria Reyes',
    email: 'maria.reyes@university.edu.ph',
    accountStatus: 'active',
    hasTempPassword: false,
    createdAt: '2025-04-01T09:05:00',
  },
  {
    id: 'staff-003',
    firstName: 'Jose',
    lastName: 'Mendoza',
    fullName: 'Dr. Jose Mendoza',
    email: 'jose.mendoza@university.edu.ph',
    accountStatus: 'active',
    hasTempPassword: true,
    createdAt: '2025-04-15T10:30:00',
  },
  {
    id: 'staff-004',
    firstName: 'Ana',
    lastName: 'Villanueva',
    fullName: 'Dr. Ana Villanueva',
    email: 'ana.villanueva@university.edu.ph',
    accountStatus: 'inactive',
    hasTempPassword: false,
    createdAt: '2025-03-20T08:00:00',
  },
  {
    id: 'staff-005',
    firstName: 'Carlos',
    lastName: 'Tan',
    fullName: 'Dr. Carlos Tan',
    email: 'carlos.tan@university.edu.ph',
    accountStatus: 'active',
    hasTempPassword: true,
    createdAt: '2025-05-01T11:00:00',
  },
]

// ─── Documents (for app-001 Juan dela Cruz) ────────────────────────────────────
export const applicantDocuments = [
  {
    id: 'doc-001',
    applicantId: 'app-001',
    documentType: 'Transcript of Records',
    fileName: 'delacruz_tor.pdf',
    fileSize: '1.2 MB',
    verified: 'verified',
    uploadedAt: '2025-05-15T14:30:00',
  },
  {
    id: 'doc-002',
    applicantId: 'app-001',
    documentType: 'Curriculum Vitae',
    fileName: 'delacruz_cv.pdf',
    fileSize: '856 KB',
    verified: 'verified',
    uploadedAt: '2025-05-15T14:32:00',
  },
  {
    id: 'doc-003',
    applicantId: 'app-001',
    documentType: 'Board Certificate / PRC License',
    fileName: 'delacruz_prc.pdf',
    fileSize: '420 KB',
    verified: 'unverified',
    uploadedAt: '2025-05-15T14:35:00',
  },
  {
    id: 'doc-004',
    applicantId: 'app-001',
    documentType: 'Service Record',
    fileName: 'delacruz_service_record.pdf',
    fileSize: '640 KB',
    verified: 'verified',
    uploadedAt: '2025-05-15T14:38:00',
  },
]

// ─── Recent Activity ──────────────────────────────────────────────────────────
export const recentActivity = [
  {
    id: 'act-001',
    applicantName: 'Juan dela Cruz',
    position: 'Assistant Professor I — DIT',
    previousStatus: 'applied',
    newStatus: 'for_interview',
    timestamp: '2025-05-17T10:30:00',
  },
  {
    id: 'act-002',
    applicantName: 'Robert Reyes',
    position: 'Assistant Professor III — COE',
    previousStatus: 'for_interview',
    newStatus: 'hired',
    timestamp: '2025-05-16T15:00:00',
  },
  {
    id: 'act-003',
    applicantName: 'Ana Gonzalez',
    position: 'Associate Professor II — CBA',
    previousStatus: 'applied',
    newStatus: 'for_review',
    timestamp: '2025-05-15T13:00:00',
  },
  {
    id: 'act-004',
    applicantName: 'Carmen Villanueva',
    position: 'Associate Professor II — CBA',
    previousStatus: 'applied',
    newStatus: 'for_review',
    timestamp: '2025-05-15T09:45:00',
  },
  {
    id: 'act-005',
    applicantName: 'Miguel Torres',
    position: 'Assistant Professor I — DIT',
    previousStatus: 'applied',
    newStatus: 'for_interview',
    timestamp: '2025-05-14T16:20:00',
  },
]
